### ISSUE TITLE
Download Link on Readme.md is wrong

### ISSUE THREAD

**Issue by BrainSlugs83** [github/GitPad#22]
The download link from readme.md is broken.

**Comment by shiftkey** [comment]
Looks like we should bundle up a new release anyway. Thanks for the tip.

**Comment by BlackPropeller** [comment]
Yeah i just ran into this issue too! Amazon AWS download link is busted :(

**Comment by jasonwilliams200OK** [comment]
What is the correct link here?

**Comment by charlesmilette** [comment]
Still broken... Any fix or alt download link yet, cause all I was able to find dates from 2012, and I'll love to use GitPad in it's latest version... Without manually compiling it...

**Comment by Haacked** [comment]
Sorry it took so long. Fixed in 4ec9b6ac88c31c9635ef2a20aee5b0a8e1cc84e3

The current release is 1.4.0 and can be found in the releases section or by clicking https://github.com/github/GitPad/releases/download/v1.4.0/Gitpad.zip
