### ISSUE TITLE
GitPad doesn't work from an elevated command prompt

### ISSUE THREAD

**Issue by BrainSlugs83** [github/GitPad#23]
When attempting to perform a "git commit" operation, it fails with the following message:

    ---------------------------
    App is Elevated
    ---------------------------
    Run this application as a normal user (not as Elevated Administrator)
    ---------------------------
    OK   
    ---------------------------

I didn't launch the command session as an administrator (and it doesn't say "- Administrator" in the title), but it still says this, so that's got to be a bug.  Not sure what else to try here.

Additionally: why should it matter? (normally, I would like to run my command sessions as an administrator.) -- I guess this is more of a feature request: please remove this requirement.  (I'm pretty sure in the past I've used GitPad from an administrative command prompt.)

**Comment by BrainSlugs83** [comment]
I usually make the following two settings changes on a new machine -- I had not yet made them on this machine -- once I made the following two setup changes the issue goes away.  But still very odd.

1. [Win+R always run as administrator](http://superuser.com/a/839874/77931)
2. [Link Administrator Profile with Regular Profile](http://www.winability.com/how-to-make-elevated-programs-recognize-network-drives/)

Running windows 8.1.

**Comment by michelemottini** [comment]
This should have been fixed: https://github.com/github/GitPad/commit/15d0a9a9c1d90266ea5556abe2145e02f5a6840d
