### ISSUE TITLE
Git for Windows can work with notepad directly

### ISSUE THREAD

**Issue by linquize** [github/GitPad#31]
Since Git for windows 2.5.3, it can work with notepad directly.

https://github.com/git-for-windows/git/issues/381

What about this project?

**Comment by shiftkey** [comment]
GitPad launches whatever editor you have selected for `.txt` under File Associations, so it isn't necessary restricted to just `notepad.exe`

**Comment by linquize** [comment]
IC

**Comment by shiftkey** [comment]
I'll close this out unless there are further questions...
